### ISSUE TITLE
Window is not correctly shown 

### ISSUE THREAD

**Issue by uzername** [NogginBops/ImGui.NET_OpenTK_Sample#7]
I have downloaded your sample, restored packages and started it. To make it look more clear, I have set GL.ClearColor to white: `GL.ClearColor(new Color4(255, 255, 255, 255));`

Window is not rendered correctly, text is not readable:

![image](https://user-images.githubusercontent.com/864126/83511437-50dff580-a4d7-11ea-8508-f2608115e3b7.png)

**Comment by uzername** [comment]
It looked similar with a color specified in original repo

**Comment by NogginBops** [comment]
@uzername If you are able to, could you open the project using [RenderDoc](https://renderdoc.org) and send me a capture?

Basically you start the program through RenderDoc and then save the capture. It would be a great help for getting a clue as to why this issue is happening.
https://renderdoc.org/docs/how/how_capture_frame.html

I would also greatly appreciate if you could tell me what os, .net version, and gpu you are using as that could also help in figuring out what the problem is. 🙂

**Comment by NogginBops** [comment]
@uzername This should be fixed with the latest commit.
Can you try and see if it's fixed?

**Comment by uzername** [comment]
![image](https://user-images.githubusercontent.com/864126/83597323-b7185700-a56f-11ea-9fe8-80366114fa52.png)

It works now, thanks

**Comment by uzername** [comment]
![image](https://user-images.githubusercontent.com/864126/83597502-27bf7380-a570-11ea-8855-f245d3977dab.png)

Now window may disappear

**Comment by jbracey2004** [comment]
@uzername , were you able to get the RenderDoc capture? I ran into the same issue, but was unable to get RenderDoc to start the program. 
I will try again later.

**Comment by jbracey2004** [comment]
@NogginBops, quick update, I don't know if this will help, but I stumbled upon this [Reddit post about to gl buffers](https://www.reddit.com/r/opengl/comments/aifvjl/glnamedbufferstorage_vs_glbufferdata/?utm_medium=android_app&utm_source=share) .
It's about glBufferData, but it also mentions something about how in OpenGL 4.4+ you cannot resize a buffer, you have to delete it. I know your code does not use glBufferData, but glNamedBufferData, but I heard that the glNamedBufferData is exclusive to OpenGL 4.5+. I wonder if this is the issue.
Only way to know for sure is if I test it, so I will see what happens if I have it delete the old buffer and create a new one when resizing.
Also I'm still curious about what OpenGL is actually doing giving the current code, so I will still try to get that RenderDoc capture.

**Comment by uzername** [comment]
I got RenderDoc, but when I launch this program with RenderDoc window stays on place. When I launch it WITHOUT RenderDoc a window can disappear. It tends to disappear when I move pointer ove Menu

**Comment by NogginBops** [comment]
@uzername I've just created an `opengl3.3` branch that only uses functions actually available in 3.3 (it actually used a few 4.5 features). 
The master branch is updated to use opengl 4.5.

So if you could test is the issue persists on both versions or if the issue is fixed I would greatly appreciate that.

**Comment by jbracey2004** [comment]
@NogginBops Good News: I was able to get the sample to work correctly by having the buffers deleted before recreating them when resizing. Below is the corrected code:
`uint totalVBSize = (uint)(draw_data.TotalVtxCount * Unsafe.SizeOf<ImDrawVert>());
            if (totalVBSize > _vertexBufferSize)
            {
                int newSize = (int)Math.Max(_vertexBufferSize * 1.5f, totalVBSize);
                GL.DeleteBuffer(_vertexBuffer);
                Util.CreateVertexBuffer("ImGui", out _vertexBuffer);
                GL.NamedBufferData(_vertexBuffer, newSize, IntPtr.Zero, BufferUsageHint.DynamicDraw);
                GL.VertexArrayVertexBuffer(_vertexArray, 0, _vertexBuffer, IntPtr.Zero, Unsafe.SizeOf<ImDrawVert>());
                _vertexBufferSize = newSize;
                Console.WriteLine($"Resized vertex buffer to new size {_vertexBufferSize}");
            }

            uint totalIBSize = (uint)(draw_data.TotalIdxCount * sizeof(ushort));
            if (totalIBSize > _indexBufferSize)
            {
                int newSize = (int)Math.Max(_indexBufferSize * 1.5f, totalIBSize);
                GL.DeleteBuffer(_indexBuffer);
                Util.CreateElementBuffer("ImGui", out _indexBuffer);
                GL.NamedBufferData(_indexBuffer, newSize, IntPtr.Zero, BufferUsageHint.DynamicDraw);
                GL.VertexArrayElementBuffer(_vertexArray, _indexBuffer);
                _indexBufferSize = newSize;
                Console.WriteLine($"Resized index buffer to new size {_indexBufferSize}");
            }`
Also note, I also have a [forked version](https://github.com/jbracey2004/ImGui.NET_OpenTK_Sample) that uses the old-fashioned glBuffer calls instead of the glNamedBuffer calls. It seems to be able to resize buffers without having to delete and recreate them.

**Comment by uzername** [comment]
opengl 3.3 branch works like a charm ! No flickering, window is not disappearing. Good!

**Comment by NogginBops** [comment]
@uzername I thought I would let you know that I just discovered a problem with the projection matrix that is used, and it's making the text blurry.
When creating the projection matrix the call should look like this:
```cs
Matrix4 mvp = Matrix4.CreateOrthographicOffCenter(
                0.0f,
                io.DisplaySize.X,
                io.DisplaySize.Y,
                0.0f,
                -1.0f,
                1.0f);
```
The change is that the first argument is changed from `-1.0` to `0.0`.

**Comment by LuisMerinoP** [comment]
Just as info, with the @jbracey2004 code that deletes the buffer when resized the sample works in the default branch "opentk4.0". Without this fix this problem persists (imgui disappears eventually on mouse move or when the imgui window is clicked). Although that is corrected in the "opentk4.0-dev" branch, in case the code wants to be corrected in the considered latest working version in the default branch.
